### ISSUE TITLE
Prospect

### ISSUE THREAD

**Issue by liach** [FabricMC/mapping-io#1]
Hello modmuss and player, I just wonder about the prospect of this project.

From a first glance, this appears to be a more efficient replacement for most available mapping libraries such as forge ones and the tiny mapping parser. Will this totally replace mapping parser, at least?

**Comment by sfPlayer1** [comment]
It may be more efficient, but the main benefits are around flexibility like being able to reshape or compose mappings, more convenience and broad format support. It should be possible to replace all other parsers+writers with this, but for this exact moment the primary purpose is remove the duplication between my implementations (matcher, bot, tr), evaluate the new visitor design and give loom's parchment something to work with.

**Comment by NebelNidas** [comment]
I'm going to close this since we now have a README.
