### ISSUE TITLE
An editor config is not present

### ISSUE THREAD

**Issue by haykam821** [FabricMC/mapping-io#2]
Unlike other repositories on the @FabricMC organization, this repository lacks an [editor config](https://editorconfig.org/).

**Comment by liach** [comment]
If you do need a config, I think the player eclipse editor config he once gave me can suffice. https://gist.github.com/d21e4b116fe4380b80845a7dd9f7a7ce

**Comment by haykam821** [comment]
I was meaning the `.editorconfig` file like [the one](https://github.com/FabricMC/fabric-loader/blob/da6632f23f80910ba8272f360185842c6a24e0cb/.editorconfig) that is on the Fabric loader repository. It doesn't need to do much other than set indentation standards.
