### ISSUE TITLE
Merging Enigma files into trees deletes dst names

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/mapping-io#24]
Causes FabricMC/fabric-loom#714.

Example:

> mappingsA/Test.mapping
```
CLASS a Test
	CLASS b Foo
		FIELD a foo Ljava/lang/String;
```
> mappingsB/a.mapping
```
CLASS a
	CLASS b
		FIELD a bar Ljava/lang/String;
```

Read `mappingsA`, then `mappingsB` into a `MemoryMappingTree`.

Expected: `a$b` has the dst name `Test$Foo`  
Found: `a$b`'s dst name has been erased by the second read call and replaced by `a$b` (or `Test$b`? I might've made a typo here)

**Comment by Juuxel** [comment]
https://github.com/FabricMC/mapping-io/blob/597f0722d6fa6faad6a790ae1c159eabf79e3022/src/main/java/net/fabricmc/mappingio/format/EnigmaReader.java#L98

I think it's caused by this line here

**Comment by sfPlayer1** [comment]
https://github.com/FabricMC/mapping-io/pull/11/commits/bc112b983dd704dd8fe081252332753ca3c7ecb0 might fix this

**Comment by NebelNidas** [comment]
@Juuxel Can you try latest master to see if this still happens?
