### ISSUE TITLE
Calling MappingReader.read with an unsupported format results in an undescriptive exception

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/mapping-io#25]
When one of the read methods is passed an unsupported format (apart from MCP), the code throws an IllegalStateException with no message:

https://github.com/FabricMC/mapping-io/blob/597f0722d6fa6faad6a790ae1c159eabf79e3022/src/main/java/net/fabricmc/mappingio/MappingReader.java#L190-L191

IllegalStateException isn't really appropriate here ("Signals that a method has been invoked at an illegal or inappropriate time."), and the user gets no useful information from the exception since it has no message either.

**Comment by sfPlayer1** [comment]
https://github.com/FabricMC/mapping-io/pull/11/commits/bc87873dda2d6cd140afdc3771ce038a2cf27fc9 adds an explicit check

The quoted code wasn't supposed to verify that the format is compatible with Reader, but to detect cases that shouldn't happen (switch didn't match somehow..)

**Comment by NebelNidas** [comment]
Since every format MIO supports now has a reader available (and I guess we're going to enforce this from now on), I'm going to close this.
