### ISSUE TITLE
TsrgFileReader doesn't support flat structure

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/mapping-io#39]
Format example:
```
test/TestClass myField a
test/TestClass myMethod ()V b
```

Mixin's [MappingWriterTSrg](https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/ap/java/org/spongepowered/tools/obfuscation/mapping/fg3/MappingWriterTSrg.java) writes these files so it'd be nice to be able to read them as well.

**Comment by NebelNidas** [comment]
That's technically CSRG, not TSRG (only differs in the hierarchical vs flat structure)

**Comment by Juuxel** [comment]
I see, I was just following Mixin's naming on this 😅

**Comment by NebelNidas** [comment]
I'm adding support for it anyway ;)
