### ISSUE TITLE
Make tiny-remapper an optional dep

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/mapping-io#59]
Right now MIO depends on tiny remapper, as TR is not on maven central you must also use the fabric maven to resolve TR. We should remove TR as a dep from the maven pom.

**Comment by modmuss50** [comment]
I think we will split this out into a `mapping-io-jvm` or `mapping-io-jvm-extras` module.

**Comment by Juuxel** [comment]
`mapping-io-jvm` sounds weird considering MIO only contains code for *JVM* deobfuscation mappings in the first place.

**Comment by modmuss50** [comment]
> `mapping-io-jvm` sounds weird considering MIO only contains code for _JVM_ deobfuscation mappings in the first place.

Yeah, thats true, I think @NebelNidas was thinking that the current MIO can work for andorid but im not sure we need to make that split. Maybe just `mapping-io-extras`?

**Comment by NebelNidas** [comment]
> thinking that the current MIO can work for andorid

Yeah, we're already using it in JADX, the only open-source Android app/Dalvik decompiler: https://github.com/skylot/jadx/tree/d129be7e863353252f4ed78f6bc208544fbe7921/jadx-plugins/jadx-rename-mappings

> MIO only contains code for JVM deobfuscation mappings in the first place.

_Yet_, maybe that will change in the future, who knows? Especially with Player's novel plans regarding Fabric Loader. So I'd still prefer `mapping-io-jvm-extras` or `mapping-io-extras-jvm`, but don't want to bikeshed for too long either, if required the name can always be changed later on anyway

**Comment by NebelNidas** [comment]
Addressed via #63.
