### ISSUE TITLE
Sorting mappings

### ISSUE THREAD

**Issue by liach** [FabricMC/mapping-io#9]
I am trying to migrate yarn to use mapping io than stitch. In the process, I find that mapping io's output order is arbitrary; since it's quite hard to sort mappings manually, I wish mapping-io can allow memory mapping trees to be sorted by, say, src names, and have easily debuggable outputs (the previous outputs of yarn are alphabetically ordered as well, and @sfPlayer1 has proposed to use the order as a way to quickly peek classes for a file-backed mapping tree)

**Comment by Col-E** [comment]
Was linked this repo just a bit ago, but at a glance it looks like you could make a visitor implementation that pipes things into a custom model that implements comparable, then sort the list of entries in the model, and print that model back out using the writers here.

**Comment by sfPlayer1** [comment]
For trees I already implemented https://github.com/FabricMC/mapping-io/pull/13

**Comment by NebelNidas** [comment]
Is sorting without trees even something we should care about? A potential adapter would need to store the entries in a tree-like structure anyway

**Comment by NebelNidas** [comment]
Closing this now, feel free to re-open if you feel such an adapter would be appropriate.
