### ISSUE TITLE
Allow multiple source namespaces

### ISSUE THREAD

**Issue by SpaceWalkerRS** [FabricMC/mapping-io#95]
related to [fabric-loom#1026](https://github.com/FabricMC/fabric-loom/pull/1026)

To my understanding, the current Tiny format allows for a single source namespace, which for classes consists of the source name, and for fields and methods the source name and the source descriptor. Then there can be any number of target namespaces, which for all types is just the target name.

To allow merged mappings for pre-1.3 Minecraft versions, however, two source namespaces are required, for the client and server sides. The client and server are obfuscated differently for these versions, so the names and descriptors do not match, and both will need to be listed.

If MIO alllowed for this, then Loom could properly support merging the client and server for these versions.

**Comment by Juuxel** [comment]
Why does the format need an extra source namespace instead of just having one of the envs as a destination namespace?

The descriptors are mapped the same way they're mapped for any other namespace, and the names are naturally separate when using another namespace.

The source namespace is not very unique other than the fact that the descs are specified in it (and the source namespace of a mapping set can be switched without any loss of data -- the descriptors can be computed).

Unless the descriptors are conflicting (which would prevent merging the jars), it doesn't really matter which ns is the source.

(Correct issue to comment on this time 😅)

**Comment by SpaceWalkerRS** [comment]
The source namespace has the descriptors so that the correct jar member can be identified and a name from another namespace can be applied.

I suppose you could add the descriptor in any other namespace and translate them to the source namespace, though in most cases you need them in the source namespace so just listing them there is more convenient. 

For merged client-server mappings though, you cannot necessarily translate between them. If the member exists on both sides you could conceivably translate the descriptor from client to intermediary and then back to server. But what about client only members, or serer only members? They must have the descriptor listed in the one source namespace that exists. 

Though I just thought, you could just make the intermediary namespace the source, and add the client and server as target namespaces that can be empty? That might work for this.

**Comment by thecatcore** [comment]
> Though I just thought, you could just make the intermediary namespace the source, and add the client and server as target namespaces that can be empty? That might work for this.

That's what cursed-fabric/babric seems to be doing with their "glued" intermediary.

**Comment by Juuxel** [comment]
> Though I just thought, you could just make the intermediary namespace the source, and add the client and server as target namespaces that can be empty? That might work for this.

Yeah, I'd just use the namespace where all types are guaranteed to be named. Then all descriptors will be available in one ns, so there's no need for multiple source namespaces in those cases.

**Comment by SpaceWalkerRS** [comment]
alright that sounds good - I'll close this issue then
